# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

stages: 
- stage: 'Build'
  jobs:
  - job:
    pool:
      name: Self-Windows
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: |
        npm install --global yarn
        yarn config set python C:\Users\hassa\AppData\Local\Programs\Python\Python311\python.exe
        yarn run build
      displayName: 'yarn install and build'

    - script: |
        npm install --global jest
        npm run test -- --coverage --coverageReporters=text-lcov
      displayName: 'Run Jest tests and generate coverage report'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.lcov'
        reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
      displayName: 'Publish code coverage report'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/'
        includeRootFolder: true
        archiveFile: '$(Build.ArtifactStagingDirectory)/express-app.zip'
    
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'express-app'
        pathToPublish: '$(Build.ArtifactStagingDirectory)/express-app.zip'


- stage: 'Dev'
  jobs:
  - job: 'Deploy'
    pool:
      name: Self-Windows
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'express-app'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download Artifact'
    - script: |
        cd $(System.ArtifactsDirectory)/express-app
        npm install --global yarn pm2
        yarn install
        pm2 restart app.js
      displayName: 'Deploy to Dev'

- stage: 'QAT'
  jobs:
  - job: 'Deploy'
    pool:
      name: Self-Windows
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'express-app'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download Artifact'
    - script: |
        cd $(System.ArtifactsDirectory)/express-app
        npm install --global yarn pm2
        yarn install
        pm2 restart app.js
      displayName: 'Deploy to QAT'

- stage: 'Staging'
  jobs:
  - job: 'Deploy'
    pool:
      name: Self-Windows
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'express-app'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download Artifact'
    - script: |
        cd $(System.ArtifactsDirectory)/express-app
        npm install --global yarn pm2
        yarn install
        pm2 restart app.js
      displayName: 'Deploy to Staging'

- stage: 'Production'
  jobs:
  - job: 'Deploy'
    pool:
      name: Self-Windows
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'express-app'
        downloadPath: '$(System.ArtifactsDirectory)'
      displayName: 'Download Artifact'
    - script: |
        cd $(System.ArtifactsDirectory)/express-app
        npm install --global yarn pm2
        yarn install
        pm2 restart app.js
      displayName: 'Deploy to Production'