# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Self-Windows

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: npm run test -- --coverage --coverageReporters=text-lcov | tee coverage.lcov
  displayName: 'Run Jest tests and generate coverage report'

- task: PublishCodeCoverageResults@1
  inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.lcov'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  displayName: 'Publish code coverage report'
